// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trfymehvpkuovzhsbwul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZnltZWh2cGt1b3Z6aHNid3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTE1ODQsImV4cCI6MjA2NTQ2NzU4NH0.8Fq9C2YWktOvKknIPutxhOyfznzDzG1P7BuS1nkwBB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);